### ISSUE TITLE
Deadlock at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()

### ISSUE THREAD

**Issue by ermau** [thomaslevesque/XamlAnimatedGif#2] opened 2014-12-29 04:42 UTC
I'm supplying a bound in `FileStream` to `AnimationBehavior.SourceStream`. The image appears to load (as pushes other items in the `ListBox` away to take up its size), but immediately after my application deadlocks. The main thread always has a callstack of:

```
 	[Managed to Native Transition]	
>	PresentationCore.dll!System.Windows.Media.Composition.DUCE.Channel.SyncFlush()	Unknown
 	PresentationCore.dll!System.Windows.Media.MediaContext.NotifySyncModeStatus(int enabledResult)	Unknown
 	PresentationCore.dll!System.Windows.Media.MediaContext.NotifyChannelMessage()	Unknown
 	PresentationCore.dll!System.Windows.Media.MediaContextNotificationWindow.MessageFilter(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(object source, System.Delegate method, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame frame)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame frame)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.Run()	Unknown
 	PresentationFramework.dll!System.Windows.Application.RunDispatcher(object ignore)	Unknown
 	PresentationFramework.dll!System.Windows.Application.RunInternal(System.Windows.Window window)	Unknown
 	PresentationFramework.dll!System.Windows.Application.Run(System.Windows.Window window)	Unknown
 	PresentationFramework.dll!System.Windows.Application.Run()	Unknown
 	Test.exe!Test.App.Main()	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.AppDomain.ExecuteAssembly(string assemblyFile, System.Security.Policy.Evidence assemblySecurity, string[] args)	Unknown
 	Microsoft.VisualStudio.HostingProcess.Utilities.dll!Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown
```

**Comment by thomaslevesque** [comment] 2015-01-04 01:41
OK, I tried it with a similar scenario (ListBox with images bound to a Stream property on each item), and I couldn't reproduce the issue... for me it works as expected.

I'm closing the issue for now, but if you manage to narrow down the cause of your problem, please let me know.

**Closed by thomaslevesque** 2015-01-04 01:41 UTC

**Comment by Mikolaytis** [comment] 2018-03-18 20:10
Hi, just googled this kind of issues, looks like it was video driver error or OutOfMemory
